# Generated by Django 2.0.2 on 2018-02-23 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['rank']},
        ),
        migrations.AddField(
            model_name='ad',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.Category', verbose_name='Categoria'),
        ),
    ]
