# Generated by Django 2.0.2 on 2018-02-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='noticia',
            table='noticias',
        ),
    ]
