# Generated by Django 2.0.2 on 2018-02-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('message', models.CharField(max_length=255, verbose_name='Mensagem')),
                ('model_name', models.CharField(max_length=100, verbose_name='Nome do Modelo')),
                ('model_id', models.IntegerField(verbose_name='ID do Modelo')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created'],
            },
        ),
    ]
